### ISSUE TITLE
wasi_snapshot_preview1.random_get nil pointer dereference (Go 1.21rc2 built application panics)

### ISSUE THREAD

**Issue by leighmcculloch** [tetratelabs/wazero#1561] opened 2023-07-06 03:44 UTC
**Describe the bug**

A basic application build with Go 1.21rc2 when loaded into the wazero runtime panics when the `random_get` wasi host function is called.

**To Reproduce**

Build a wasm that doesn't do anything:

```go
package main
func main() { }
```

```
GOOS=wasip1 GOARCH=wasm go build -o main.wasm main.go
```

Build a host using wazero v1.2.1 a host that supports wasip1:

```go
package main

import (
	"context"
	_ "embed"
	"fmt"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1"
)

//go:embed main.wasm
var wasm []byte

func main() {
	ctx := context.Background()

	r := wazero.NewRuntime(ctx)
	defer r.Close(ctx)

	_, err := wasi_snapshot_preview1.Instantiate(ctx, r)
	if err != nil {
		panic(err)
	}

	mod, err := r.Instantiate(ctx, wasm)
	if err != nil {
		panic(err)
	}

	f := mod.ExportedFunction("_start")
	if f != nil {
		res, err := f.Call(ctx)
		if err != nil {
			panic(err)
		}
		fmt.Println("start =", res)
	}
}
```

Run the host Go application.

**Expected behavior**

The application to execute.

**Actual behavior**
```
go run ./host
panic: runtime error: invalid memory address or nil pointer dereference (recovered by wazero)
wasm stack trace:
        wasi_snapshot_preview1.random_get(i32,i32) i32
        .runtime.random_get(i32) i32
        .runtime.getRandomData(i32) i32
        .runtime.alginit(i32) i32
        .runtime.schedinit(i32) i32
        .runtime.rt0_go(i32) i32
        ._rt0_wasm_wasip1()

Go runtime stack trace:
goroutine 1 [running]:
runtime/debug.Stack()
        /Users/leighmcculloch/.local/bin/go/latest/src/runtime/debug/stack.go:24 +0x64
github.com/tetratelabs/wazero/internal/wasmdebug.(*stackTrace).FromRecovered(0x140004277e0?, {0x100a6dcc0?, 0x100d1d8a0?})
        /Users/leighmcculloch/.local/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.2.1/internal/wasmdebug/debug.go:139 +0xc4
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).deferredOnCall(0x14000000360, {0x100aa3740, 0x100d5cbe0}, 0x100aa5358?, {0x100a6dcc0, 0x100d1d8a0})
        /Users/leighmcculloch/.local/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.2.1/internal/engine/compiler/engine.go:855 +0x37c
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).call.func1()
        /Users/leighmcculloch/.local/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.2.1/internal/engine/compiler/engine.go:732 +0x68
panic({0x100a6dcc0?, 0x100d1d8a0?})
        /Users/leighmcculloch/.local/bin/go/latest/src/runtime/panic.go:914 +0x218
github.com/tetratelabs/wazero/internal/sys.(*Context).RandSource(...)
        /Users/leighmcculloch/.local/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.2.1/internal/sys/sys.go:109
github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1.randomGetFn({0x0?, 0x100d567b0?}, {0x100aa5358?, 0x14000163a40?}, {0x14000134110?, 0x100a72c40?, 0x14000427c01?})
        /Users/leighmcculloch/.local/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.2.1/imports/wasi_snapshot_preview1/random.go:41 +0x3c
github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1.wasiFunc.Call(0x1289dc3e8?, {0x100aa3740?, 0x100d5cbe0?}, {0x100aa5358?, 0x14000163a40?}, {0x14000134110, 0x2, 0x0?})
        /Users/leighmcculloch/.local/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.2.1/imports/wasi_snapshot_preview1/wasi.go:293 +0x58
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).execWasmFunction(0x14000000360, {0x100aa3740, 0x100d5cbe0}, 0x100e5c108?)
        /Users/leighmcculloch/.local/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.2.1/internal/engine/compiler/engine.go:1024 +0x118
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).call(0x14000000360, {0x100aa3740, 0x100d5cbe0}, {0x0?, 0x14000427e48?, 0x10099f84c?}, {0x0, 0x0, 0x0})
        /Users/leighmcculloch/.local/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.2.1/internal/engine/compiler/engine.go:747 +0x224
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).Call(0x14000163a40?, {0x100aa3740?, 0x100d5cbe0?}, {0x0?, 0x153849?, 0x153849?})
        /Users/leighmcculloch/.local/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.2.1/internal/engine/compiler/engine.go:701 +0xc0
main.main()
        /Users/leighmcculloch/Code/wazero-play/host/main.go:33 +0x13c


goroutine 1 [running]:
main.main()
        /Users/leighmcculloch/Code/wazero-play/host/main.go:35 +0x1c4
```

**Screenshots**
N/A

**Environment (please complete the relevant information):**
- Go version: 1.21rc2
- wazero Version: v1.2.1
- Host architecture: macOS arm64
- Runtime mode: interpreter

**Additional context**

**Comment by codefromthecrypt** [comment] 2023-07-06 04:23
one note is that _start is already called by `Instantiate` unless ModuleConfig.WithStartFunctions overrides that default. Calling _start twice can have problems. Does this problem exist if you don't redundantly call _start?

**Comment by codefromthecrypt** [comment] 2023-07-06 07:49
I can reproduce this error if `_start` is called redundantly.

**Comment by codefromthecrypt** [comment] 2023-07-06 07:57
The problem is that `ModuleInstance.ensureResourcesClosed` nils out the system context when the module is closed (which happens after _start returns the first time). 

We could consider double-checking to provide a better error message. To reduce performance overhead, we could check late (e.g. double-check if the module was closed at the time of the message, and say "module closed") or something.. hmm

**Comment by codefromthecrypt** [comment] 2023-07-06 07:59
open to suggestions and/or a PR cc @ncruces @ckaznocha or anyone who has mental space to move us forward!

![Screenshot 2023-07-06 at 15 57 48](https://github.com/tetratelabs/wazero/assets/64215/4c89b82e-c3ba-40ec-bf20-b40e5e3b3c73)

**Comment by leighmcculloch** [comment] 2023-07-06 07:59
Ah, yes that's what's happening. I'm trying to call the `_start` function twice. I didn't realize that wazero executed the exported function automatically. Makes sense.

**Comment by leighmcculloch** [comment] 2023-07-06 08:04
A more explicit error in the form of "exported _start function cannot be executed twice", which according to the WASI ABI docs, is something the runtime shouldn't allow to happen.
Ref: https://github.com/WebAssembly/WASI/blob/main/legacy/application-abi.md#current-unstable-abi

**Comment by codefromthecrypt** [comment] 2023-07-06 08:07
@leighmcculloch That could work.. one thing we could do is just filter out any function name in the start functions. That way other init functions could not be possible to run twice as you couldn't access them (there are others besides _start, just we default to that)

**Comment by ncruces** [comment] 2023-07-06 08:38
Go `wasip1` explicitly calls `proc_exit`, even for a "no error" return:
```sh
./wazero/cmd/wazero/wazero run -hostlogging all main.wasm 
--> ._rt0_wasm_wasip1()
	==> wasi_snapshot_preview1.random_get(buf=810944,buf_len=32)
	<== errno=ESUCCESS
	==> wasi_snapshot_preview1.random_get(buf=810736,buf_len=8)
	<== errno=ESUCCESS
	==> wasi_snapshot_preview1.clock_time_get(id=monotonic,precision=0)
	<== (timestamp=380156302238933,errno=ESUCCESS)
	==> wasi_snapshot_preview1.args_sizes_get(result.argc=830492,result.argv_len=830488)
	<== errno=ESUCCESS
	==> wasi_snapshot_preview1.args_get(argv=21020680,argv_buf=21020688)
	<== errno=ESUCCESS
	==> wasi_snapshot_preview1.environ_sizes_get(result.environc=830480,result.environv_len=830484)
	<== errno=ESUCCESS
	==> wasi_snapshot_preview1.clock_time_get(id=monotonic,precision=0)
	<== (timestamp=380156323231365,errno=ESUCCESS)
	==> wasi_snapshot_preview1.clock_time_get(id=monotonic,precision=0)
	<== (timestamp=380156323238570,errno=ESUCCESS)
	==> wasi_snapshot_preview1.clock_time_get(id=monotonic,precision=0)
	<== (timestamp=380156323332489,errno=ESUCCESS)
	==> wasi_snapshot_preview1.clock_time_get(id=monotonic,precision=0)
	<== (timestamp=380156323391276,errno=ESUCCESS)
	==> wasi_snapshot_preview1.clock_time_get(id=monotonic,precision=0)
	<== (timestamp=380156323418316,errno=ESUCCESS)
	==> wasi_snapshot_preview1.proc_exit(rval=0)
```

Calling `_start` repeatedly is _discouraged_ (because libc init runs multiple times) but wont panic on a minimal C program (built with `wasi-sdk`), if you `return 0`:
```c
int main(int argc, char *argv[]) {
  return 0;
}
```

```sh
./wazero/cmd/wazero/wazero run -hostlogging all a.out               
--> ._start()
	==> wasi_snapshot_preview1.args_sizes_get(result.argc=67064,result.argv_len=67068)
	<== errno=ESUCCESS
	==> wasi_snapshot_preview1.args_get(argv=67104,argv_buf=67088)
	<== errno=ESUCCESS
<--
```

**Comment by evacchi** [comment] 2023-07-06 12:43
I also see nothing _inherently_ wrong about invoking `_start` more than once, even though it may not be exactly what you want. 

At the beginning, I myself did find slightly surprising that `Instantiate`ing a module _also_ causes the startup function to be run, but that's part of the model; arguably, you should be able to make it more predictable by configuring your module with an empty list of start functions:

```
config := wazero.NewModuleConfig().WithArgs(/*...*/).WithStartFunctions() // <-- notice the empty argument list
```

this inhibits the automated execution, allowing you to instantiate first, and then separately invoke `_start` explicitly:

```
	mod, err := r.InstantiateWithConfig(ctx, bin, config)
	...
	res, err := mod.ExportedFunction("_start").Call(ctx)
```

**Comment by ncruces** [comment] 2023-07-06 13:02
> I also see nothing _inherently_ wrong about invoking `_start` more than once, even though it may not be exactly what you want.

That may be true for WASM in conceptually, but it's going to depend heavily on what your WASM+WASI compiler generates.

`go` calls exit at the end of main and then it's done. Also for sure it's doing init stuff (running `init` functions), and probably not guarding those for multiple runs, which violates the Go spec.

`wasi-sdk` `clang` is initing `wasi-libc` and running other constructor functions even before calling your `main`. Any of those may not expect to run multiple times, and not from a clean state.

`tinygo`, `rust` I have no idea, but I've seen bugs about running `_start` multiple times on `wasmtime` for stuff compiled with `rust`.

So for WASI commands it's expected/valid that they expect `_start` to be called exactly once, and likely that nothing else may be called afterwards. WASI reactors expect `_initialized`

**Comment by evacchi** [comment] 2023-07-06 14:02
fair enough, I mean invoking more than once a constructor on an object or init() on a module indeed would make no sense... 🤔

**Comment by codefromthecrypt** [comment] 2023-07-06 23:46
yeah I think in go community jargon this one classifies as a "foot gun". I'll raise a PR to remove start functions from the export list (while not actually removing them from the module)

**Comment by leighmcculloch** [comment] 2023-07-07 02:59
Removing the functions from the list of exported functions might make the API of wazero a little awkward to work with. For example, in some code I've been toying with I want to list out all exported functions. If the start/initialize is magically omitted from the list sometimes, that would be unintuitive as to why they aren't showing up in the list.

I don't think there's really anything to do about the above, other than to maybe improve the documentation about the `Instantiate` function to explicitly state that functions are automatically executed unless configured not to.

**Comment by ckaznocha** [comment] 2023-07-07 03:11
Leaving the start function in the export list but making it return a helpful error if it's ever called by user code might be a reasonable middle ground.

**Comment by codefromthecrypt** [comment] 2023-07-07 03:47
OK, so for the sake of discussing options:
1. Document Instantiate better about start functions
2. Document Instantiate better about start functions and remove them from exports
  * there's really no reason to call an init in every case it is a bug. However, if someone disagrees they can clear the StartFunctions in ModuleConfig
3. Document Instantiate better about start functions and try to make a better error
  * this is similar to the former except more code as we have to define a special function wrapper for each start function.

I really think the best way out is 2. It is the least tech debt and calling a start function again is theoretical at best, and there's no concrete case to do that. In fact we know it will fail with `_start`. If someone feels strongly, they can still call `_start` incorrectly multiple times by clearing if from ModuleConfig as they can today.

**Comment by codefromthecrypt** [comment] 2023-07-07 04:07
since all options require docs I raised this https://github.com/tetratelabs/wazero/pull/1568

We can adjust those docs if we do something else about it.

**Comment by codefromthecrypt** [comment] 2023-07-07 04:12
sorry I forgot option 4, discussed earlier:

Don't worry about specific function names, rather guard if any exported function is called after the module is closed. This is imho better just I am worried about the cost of checking this in the compiler engine.

**Comment by leighmcculloch** [comment] 2023-07-07 05:49
> 2\. ... remove them from exports

I don't have a strong opinion on most of the options, however want to point out that option two will cause wazero's representation of a module to be incomplete. It's reasonable to ask wazero for all exported functions. Once wazero is omitting exported functions it isn't as useful as a composable utility. At least we're replacing one surprising behavior with another surprising behavior. Hiding functions in some cases and not other is pretty unintuitive.

**Comment by codefromthecrypt** [comment] 2023-07-07 05:50
I've changed my opinion to not like 2. anymore. Thanks for convincing me folks!

**Comment by leighmcculloch** [comment] 2023-07-07 06:19
One thing to consider about why it is surprising that `Instantiate` calls `_start` by itself, is that other runtimes I've used don't follow this pattern.

For example, in both NodeJS and Deno, their runtimes don't call any exported functions as part of instantiation. Their WASI libraries provide `instance.start()` and `instance.intialize()` for calling the respective `_start` or `_initialize` functions.

These two functions are defined by the WASI spec ([link](https://github.com/WebAssembly/WASI/blob/main/legacy/application-abi.md)), not WASM spec ([link](https://github.com/WebAssembly/design/blob/main/Modules.md#module-start-function)), so having wazero automatically call the exported `_start` function when not configured for WASI is unexpected.

It's also worth noting that WASM programs have a "start" function that is not the same thing as the WASI `_start` function. The WASM start function is not an exported function, but a special function that runtimes guarantee is executed before any exported function, and also has some limitations on what it can do. It's sort of like the init function that some compiled binaries have.

So actually, I think Wazero should only be trying to call an exported `_start` function if a WASM is a WASI, not for non-WASI WASMs. But it should be calling the WASM "start" function in any case, if it doesn't do this already.

**Comment by codefromthecrypt** [comment] 2023-07-07 06:23
@leighmcculloch being like other runtimes just to do that, isn't a goal of ours. We have found many places where other designs are not good in general, or make you do heavy labor by default. When we make decisions often we add RATIONALE.md which perhaps we could link in the godoc here.

https://github.com/tetratelabs/wazero/blob/main/RATIONALE.md#why-does-instantiatemodule-call-_start-by-default

**Comment by leighmcculloch** [comment] 2023-07-07 06:23
It's also worth noting that `_start` and `_initialize` are defined as part of the legacy API used by wasi_snapshot_preview1, but are unlikely to exist in wasi preview 2. I saw somewhere in the GitHub repos the very least `_start` was renamed to `run` in wasi preview 2. I'm going off the comments here:
- https://github.com/WebAssembly/WASI/issues/19#issuecomment-1589803513

**Comment by codefromthecrypt** [comment] 2023-07-07 06:27
@leighmcculloch wasip2 is still very much in flux, so we'll cross that bridge when we get there. `_start` is in use by compilers today, and even in new things like wasix. It won't interfere with wasip2 which won't define the function.

**Comment by codefromthecrypt** [comment] 2023-07-07 06:32
p.s. wazero takes 1.0 very seriously. If we removed `_start` we would break everyone. We've automatically called this on their behalf for well over a year.

When wasip2 is actionable (maybe 2024) we'll likely add that to the list so that people can transparently use it. Bear in mind that wasip2 is based on components and so there's a lot more going to happen than just the "_start" -> "run" thing. My guess is wasip2 will be defined by https://github.com/WebAssembly/wasi-cli but really we need to see any concrete use of this before making decisions about it. Since preview 2 is scheduled for fall, we'll defer that as guessing hasn't been correct for us so far..

**Comment by codefromthecrypt** [comment] 2023-07-07 07:24
added another doc pr. PS I didn't mean to close this GH misunderstood me https://github.com/tetratelabs/wazero/pull/1569

**Comment by codefromthecrypt** [comment] 2023-07-10 03:54
Chatted with @mathetake and the problem happened when we fixed something else. Basically, we used to return `ExitError` even on zero, but stopped doing that in #1284. Before, callers could have seen this error externally and avoided trying to call an export after close.

When we removed that, we didn't replace the use case of "knowing a module is closed", which someone could check in a way compatible with any compiler, prior to attempting to call a function. What we chatted about was adding a `Module.IsClosed()` or similar for folks who might attempt to use an export after a start function happened. This would allow them to avoid undefined behavior.

**Comment by codefromthecrypt** [comment] 2023-07-10 06:20
ok this exposes `Module.IsClosed` which will work for any function including a redundant call to `_start`. Personally, I will use this for ABI such as https://http-wasm.io as we can get a better error message if the binary wasn't compiled properly or someone did something strange. However, I won't call it literally on every callback.

**Closed** 2023-07-10 07:32 UTC
Labels: bug
