### ISSUE TITLE
api.Memory.Size() overflows when the memory has the maximum 65536 pages

### ISSUE THREAD

**Issue by EclesioMeloJunior** [tetratelabs/wazero#1852] opened 2023-11-29 12:44 UTC
**Describe the bug**
Basically, when calling `memory.Grow` function passing a delta that grows the memory to the `MemoryLimitPages` (65536) returns successfully but when we call `memory.Size()` the number of pages mismatches the expected.

I think that occurs because uint32 cannot fit the new buffer len (since the current page is `65536` and the number of bytes per page is `65536` and the multiplication of these values overflows uint32)

**To Reproduce**
I've wrote a test that reproduces the error in this fork https://github.com/ChainSafe/wazero/pull/4

**Expected behavior**
Since the limit is `MemoryLimitPages` we should be able get the correct page size when growing up to that size

**Screenshots**
N/A

**Environment (please complete the relevant information):**
- Go version: 1.21.3
- wazero Version: 6a7e474e022e5d325261cf3073eb246cf4fb4238
- Host architecture: arm64
- Runtime mode:

**Additional context**

**Comment by mathetake** [comment] 2023-11-30 02:04
Thank you @EclesioMeloJunior for reporting this, and I confirmed that this is actually a bug in our API. As you described, when the memory has the maximum of 65536 pages, the buffer length becomes 2^32, which is larger than the maximum of uint32 which is the return type of api.Memory Size.

We could do either 

1. Changing the return type of api.Memory Size to uint64
    - This is somewhat breaking change, though the impact should be really minimum because this is just a integer type conversion.
2. Adds another for `SizeSafe()` or whatever it is while putting deprecation comments on the api.Memory Size.
    - This won't be a breaking change 


thoughts? @evacchi @ncruces @achille-roussel

**Comment by mathetake** [comment] 2023-11-30 14:45
> what about checking in the Grow method for this limit? I mean, instead of allowing the buffer size to reach 2^32 (which overflows uint32 only by 1) check and limit the buffer size/cap to be (2^32) - 1 then it will bound to uint32 limits (and the Size will not have problems to calc/return the correct size). I would assume that the problem with this approach is that the latest page will lose 1 byte (65535 instead of 65536), right?

no that's not our option as that means wazero is not compliant with the Wasm spec.

**Comment by EclesioMeloJunior** [comment] 2023-11-30 21:29
@mathetake @ncruces thanks for the clarifications, I took the freedom to create a draft PR that introduces the new method https://github.com/tetratelabs/wazero/pull/1856

**Comment by mathetake** [comment] 2024-02-19 08:29
So we are looking to release wazero 2.0 next month, and I think we can make the breaking change to this rather than having another confusing api like `Size64`.

**Comment by mathetake** [comment] 2024-03-02 03:39
reopening this as we've decided to not fix this in 2.0, which is explained in detail in #2106

**Comment by ncruces** [comment] 2024-03-05 18:52
Maybe we could document the issue, and add a method `Pages()` that allows you to figure out the difference between 0 and 65536 pages.

**Comment by ncruces** [comment] 2024-04-04 01:57
I think we should:
1. document the issue [here](https://pkg.go.dev/github.com/tetratelabs/wazero/api#Memory).
2. note that you can obtain the number of pages of the memory by calling [`Grow(0)`](https://github.com/tetratelabs/wazero/blob/15e1eb720950ccef4c6d71c5828088c5be7a8cbf/internal/wasm/memory.go#L251-L255).
3. possibly add the _already implemented_ [`PageSize()`](https://github.com/tetratelabs/wazero/blob/15e1eb720950ccef4c6d71c5828088c5be7a8cbf/internal/wasm/memory.go#L281-L283) method to the interface.

Then we can close this? I mean, given the above, I guess the biggest deficiency is **not** the `Size()` method, rather that it's not possible for `Read()` to ever give you the full 4GB buffer.

**Comment by mathetake** [comment] 2024-04-04 08:42
regardless of having new API or not, defer to @evacchi for any decision from now!

**Closed** 2024-04-04 11:08 UTC
Labels: bug
