### ISSUE TITLE
Infinite Loop in `ssa.(*builder).resolveAlias`

### ISSUE THREAD

**Issue by clarkmcc** [tetratelabs/wazero#2329] opened 2024-10-05 00:36 UTC
**Describe the bug**
When running the compiler on Linux arm64, my module which normally runs in microseconds, will get stuck in a loop and never exit.
![image](https://github.com/user-attachments/assets/90e5523a-a0ac-4212-b356-ede88511b657)

I don't have a reproduction case, so what I'm mainly asking is what _could_ this mean? I'm using extism, I'm compiling the module, not using the interpreter, and I'm using a filesystem cache. When I switch to using the interpreter, the problem goes away.

On a side note, it seems problematic that context cancellation can't break me out of this infinite loop.

**Comment by ncruces** [comment] 2024-10-05 08:21
Does this happen when compiling the module, or when running the compiled module?

Did you try any platforms other than Linux arm64?

What does it mean that it "normally" runs in microseconds?

If it's compiling the module, why don't you have a reproducer? Don't you gave access to the Wasm, aren't you willing/allowed to share it?

**Comment by clarkmcc** [comment] 2024-10-05 13:59
I assumed it was during the compilation phase just based on the flamegraph. But if that isn't actually a safe assumption, I'll do some more testing this week and answer all your questions. I only tested on Linux arm64 as that is the only target I intent to run it on. 

Happy to provide the WASM module itself, the framework we have around running the module will be more challenging, but I'll see what I can do.

Thanks for the quick reply

**Comment by ncruces** [comment] 2024-10-05 14:55
It looks like it's under compilation given the flame graph, but as you said it “normally runs in microseconds” I seeked clarification.

From the flame graph it also seems like the same should happen on amd64, but testing that also helps narrow things down.

Another thing we can do is look at the [file with blame](https://github.com/tetratelabs/wazero/blame/6016a705fa6077f517731d4ce148a82968de02dd/internal/engine/wazevo/ssa/builder.go#L726) see when it [last changed](https://github.com/tetratelabs/wazero/pull/2285), and test with a [version before that](https://github.com/tetratelabs/wazero/releases/tag/v1.7.3).

But if you can provide the Wasm, we can more easily test it yes.

Answering another of your points, the context isn't really used to stop compilation, only runtime.

**Comment by mathetake** [comment] 2024-10-05 17:19
sorry, I tried to compile the binary (I received from @ncruces ) and that was compiled pretty much instantly. Until you can give us the real repro i am closing.

**Closed by mathetake** 2024-10-05 17:19 UTC
Labels: bug

**Comment by mathetake** [comment] 2024-10-05 17:21
and could you make sure this reproduces with the latest main - checking the version used by your extism version.

**Comment by clarkmcc** [comment] 2024-10-05 17:30
Sure, I'll work on a repro. And just to clarify, is this working for you on linux/arm64 on the main wazero?

**Comment by mathetake** [comment] 2024-10-05 17:31
for all platforms (darwin, linux) x (amd64, arm64) plus the code there is independent of the platform FWIW

**Comment by clarkmcc** [comment] 2024-10-05 18:55
So a couple interesting notes:
* I can't reproduce this running the same code on darwin/arm64. I did notice that this code appears to be platform independent, but it is interesting that I can only reproduce on my linux/arm64 environment.
* My linux/arm64 environment is actually an embedded device running armbian. It's a 4 core, 1 gb of memory device running good ole' Linux so I'm not sure why that would matter, but maybe it is relevant. It is going to make this nearly impossible to reproduce for you I am sure.

I'm working on upgrading to 1.8.1 and will test again to see if I can provide any more info.

I'm guessing there aren't any hints you can give me about what the `resolveAlias` function that could help me pin down the conditions under which it would never break out of a loop?

**Comment by ncruces** [comment] 2024-10-05 19:58
If it's Linux specific, which would be surprising, I can test Monday under qemu.

**Comment by clarkmcc** [comment] 2024-10-07 15:42
I can't seem to reproduce on my linux/arm64 embedded device with wazero 1.8.1, so this appears to be resolved.

**Comment by evacchi** [comment] 2024-10-07 16:02
good to know! :)
