### ISSUE TITLE
[question]:How do I obtain and limit the resources used by WASM? 

### ISSUE THREAD

**Issue by springrain** [tetratelabs/wazero#1533] opened 2023-06-21 15:56 UTC
How do I obtain and limit the resources used by WASM? 
Mainly CPU, memory, disk IO, execution time,.  like blockchain contract gas

**Comment by springrain** [comment] 2023-06-22 01:56
Does Wazero have any plans to enhance resource-related features? This is very useful for FaaS (Cloud Functions).

**Comment by codefromthecrypt** [comment] 2023-06-22 11:26
@springrain this is a duplicate of #422. There are notes throughout that issue and also some technical notes in https://github.com/tetratelabs/wazero/pull/1108 as to why we closed it.

You can subscribe to #422 in case something changes which allows us to re-visit the topic with new information besides demand. For now, what @ncruces mentioned is the current workaround and agree it is not the same as emulating a fuel concept.

**Closed by codefromthecrypt** 2023-06-22 11:26 UTC
Labels: enhancement
