### ISSUE TITLE
Support WASI poll_oneoff for clock events

### ISSUE THREAD

**Issue by clarkmcc** [tetratelabs/wazero#625] opened 2022-06-08 19:59 UTC
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/tetratelabs/wazero/issues/271. The following code in Rust causes the following panic.
```rust
std::thread::sleep(time::Duration::from_secs(10));
```

```
thread '<unnamed>' panicked at 'thread::sleep(): unexpected result of poll_oneoff', library/std/src/sys/wasi/thread.rs:57:22
```

**Describe the solution you'd like**
Support for the `poll_oneoff` WASI method.

**Comment by codefromthecrypt** [comment] 2022-06-15 00:10
excellent. I'll help with this unless you are game.

**Comment by codefromthecrypt** [comment] 2022-06-15 04:41
It appears this is also used in zig, though not sure the code and compilation instructions that generates the binding https://github.com/ziglang/zig/blob/0e6285c8fc31ff866df96847fe34e660da38b4a9/lib/std/time.zig#L24-L47

**Comment by codefromthecrypt** [comment] 2022-06-15 04:49
haha our own @mathetake implemented this in tinygo https://github.com/tinygo-org/tinygo/pull/1373#issuecomment-695151252

**Comment by mathetake** [comment] 2022-06-15 05:16
lol I completely forgot about that :))

**Comment by codefromthecrypt** [comment] 2022-06-15 08:16
@clarkmcc as there's more than one way to do it, if you have a moment, can you make a scratch repo to reproduce that error? I used wasm32-wasi locally and it failed but invisibly, as opposed to the error you found. I want to make sure I'm doing the same so I can sort it. Main thing is I want to iterate on this, and firstly solve the thread.sleep thing which is reasonably common across compilers.

**Comment by codefromthecrypt** [comment] 2022-06-15 23:50
thanks, @clarkmcc!

self-note: here's the wasi-libc call site for sleep, though there are other uses of poll_oneoff https://github.com/WebAssembly/wasi-libc/blob/659ff414560721b1660a19685110e484a081c3d4/libc-bottom-half/cloudlibc/src/libc/time/clock_nanosleep.c

**Comment by codefromthecrypt** [comment] 2022-06-16 03:19
I did some research and the best way to incrementally implement this is to cheat similarly to how wasmtime and wasi-libc do, where they hook into sleep when the poll event is a clock. ex https://github.com/bytecodealliance/wasmtime/pull/2753

**Comment by codefromthecrypt** [comment] 2022-06-16 03:21
by cheat I mean use one sleeper for both supported clocks (wall and nano) due to an interpretation of "clock_settime" not affecting relative time https://linux.die.net/man/3/clock_settime

**Comment by codefromthecrypt** [comment] 2022-06-16 07:47
https://github.com/tetratelabs/wazero/pull/629 works, but I need to backfill tests and check other impls

**Comment by codefromthecrypt** [comment] 2022-06-16 23:50
Notes about go-generated wasm, doesn't use wasi, rather implements sleep with nanotime.

---

`GOOS=js GOARCH=wasm` compiled wasm uses nanotime as that's what time.Sleep does internally (among atomic ops that aren't really atomic in go-generated wasm).

Ex. the following only uses nanotime when compiled with `GOOS=js GOARCH=wasm`
```go
package main

import "time"

func main() {
	time.Sleep(time.Second * 10)
}
```

related, `GOOS=js GOARCH=wasm` uses `notetsleepg` which calls both nanotime and scheduleTimeoutEvent. I'm putting timeout events out of scope even though there's some future need in wasi-clocks

cc @prep

**Comment by codefromthecrypt** [comment] 2022-06-17 04:43
verified tinygo uses what we think it does

**Comment by codefromthecrypt** [comment] 2022-06-17 05:03
verified zig thanks to @mathetake for the help gettin ziggy witit

```bash
$ zig build-exe -O ReleaseSmall -target wasm32-wasi sleep.zig
```

```zig
const std = @import("std");
pub fn main() !void {
    std.time.sleep(std.time.ns_per_s * 5);
}
```

**Closed** 2022-06-17 08:48 UTC
Labels: enhancement
